server:
  port: 8080

spring:
  profiles:
    include: secret
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    #open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    defer-datasource-initialization: true

  jwt:
    token:
      secret-key: ${SECRET_KEY}
      refresh-secret-key: ${REFRESH_SECRET_KEY}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  #  sql:
  #    init:
  #      mode:

  oauth:
    kakao:
      client_id: ${CLIENT_ID}
      redirect_uri: ${REDIRECT_URI}
      scope: profile_nickname

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 서버 재시작시 배치 자동실행 방지

#  profiles:
#    active: jwt, api

logging:
  level:
    org:
    #      springframework:
    #        orm:
    #          jpa: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG

    info:
      root: debug
    com.ssafy.jansorry: DEBUG
