server:
  port: 8080

spring:
  profiles:
    include: secret
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    #open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    defer-datasource-initialization: true

  jwt:
    token:
      secret-key: ${SECRET_KEY}
      refresh-secret-key: ${REFRESH_SECRET_KEY}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  sql:
    init:
      mode: always

  oauth:
    kakao:
      client_id: ${CLIENT_ID}
      redirect_uri: ${REDIRECT_URI}

#  profiles:
#    active: jwt, api

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
    com.ssafy.jansorry: DEBUG
